#!/bin/sh
# FIXME: Save the commit message somewhere?
#         $ git commit -F .git/COMMIT_EDITMSG
#        Results in an empty commit message in this run.

msgfile="$1"

common="You might want to fix this and retry the commit."

test -s "$msgfile" || {
	echo >&2 "Commit message must NOT be empty."
	echo >&2 "$common"
	exit 1
}

# Check first line is <= 50 chars, and followed by empty line
test "x$(sed -n '1s/^.\{,50\}//p' "$msgfile")" = "x"  || {
	echo >&2 "First line is too long. It should be <= 50 characters."
        echo >&2 "These characters fit:   $(sed -n '1s/^\(.\{,50\}\)\(.*\)$/\1/p' "$1")"
	echo >&2 "These exceed the limit: $(sed -n '1s/^\(.\{,50\}\)\(.*\)$/\2/p' "$1")"
	echo >&2 "$common"
	exit 1
}
test "x$(sed -n 's/^#.*//; 2p' "$msgfile")" = "x" || {
	echo >&2 "Second line should be empty."
	echo >&2 "$common"
	exit 1
}

